vich_uploader:
    db_driver: orm

    mappings:
        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        livres:
            uri_prefix: /images/livres
            upload_destination: '%kernel.project_dir%/public/images/livres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        auteur:
            uri_prefix: /images/auteur
            upload_destination: '%kernel.project_dir%/public/images/auteur'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        carousel:
            uri_prefix: /images/carousel
            upload_destination: '%kernel.project_dir%/public/images/carousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        avatar:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

